name: Test Library

on: pull_request

jobs:
  rftest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Jenkins image
        run: |
          docker ps
          docker build --pull -t jenkins-test atest/docker
          docker run -p 127.0.0.1:8080:8080 -e JAVA_OPTS=-Djenkins.install.runSetupWizard=false -d jenkins-test

      - name: Install library
        run: pip install .

      - name: Run robot framework tests
        run: robot --loglevel DEBUG atest/

      - name: Upload robot framework test results
        uses: actions/upload-artifact@v3
        with:
          name: robotframework-results-${{ matrix.python-version }}
          path: |
            output.xml
            log.html
            report.html
        if: ${{ always() }}
